### ISSUE TITLE
[RFE] Make scenarios collapsible individually

### ISSUE THREAD

**Issue by fpokryvk** [behave-contrib/behave-html-pretty-formatter#10]
Now, it is possible to expand/collapse scenarios based on status, but one can not collapse/expand individual scenario.

Also, this should be indicated by CSS by small arrow in the right of scenario header

**Comment by lu-maca** [comment]
Hi @fpokryvk, 
when there are multiple feature in the same report, the Collapse All/Expand All/Expand All Failed buttons are not working in the way I expected: if I click on the Collapse All of feature A summary button, I expect only the scenarios in that feature to collapse and not in all the features (feature A and B).

**Comment by fpokryvk** [comment]
Hi @lu-maca, thank you for pointing that out. It is a bug, that should be fixed. It can be done while working on this issue.

**Comment by lu-maca** [comment]
Hi @fpokryvk, 
I've worked on this issue (and on issue #13). I put here some pictures to show the result:

1)
![immagine](https://user-images.githubusercontent.com/65252677/209449052-34015a65-c808-48fa-bce3-232e8c919125.png)
2)
![immagine](https://user-images.githubusercontent.com/65252677/209449069-cccf0417-aad0-42ef-900c-d7871439e6b1.png)
3)
![immagine](https://user-images.githubusercontent.com/65252677/209449098-dc304d4e-1f7d-4800-ae3b-c3812fea9ec5.png)

I would like to change the additional-info container, since now if two or more feature are present, it is shown for each feature container. I would move it to an external container at the beginning of the page, to avoid useless repetitions.
Now that you have merged my pull request I can also work on this (but maybe I will do this in the next year, since my company is now closed!). 

You can find, if you're interested, all the changes [here](https://github.com/lu-maca/behave-html-pretty-formatter/tree/feat/scenarios-expander).

Luca

**Comment by fpokryvk** [comment]
Sure, enjoy the screen-free time! We are also closed. Thanks for the work on this! I also planned o add `^` `v` icons, I planned to search for unicode characters with unified look, in that way it would follow the font color easily and no external resource would have to be compiled into HTML. I would maybe move the "arrow" to the rightmost. Sure we can cooperate in the next year.

**Comment by lu-maca** [comment]
I'm opening a new pull request (already opened another one and closed a moment later - I'm not so used to github :smile:) for these changes, so that we can discuss them there. 

Have a nice vacation, see you next year!

**Comment by fpokryvk** [comment]
Some work is continuing here:

https://github.com/behave-contrib/behave-html-pretty-formatter/commits/fp/scenario_collapse
