### ISSUE TITLE
Disable download embed

### ISSUE THREAD

**Issue by lu-maca** [behave-contrib/behave-html-pretty-formatter#22]
Hi guys,

according to #16, it is possible to download the embedded data. This is cool if you have files/images/videos. However we simply embed text. Is it ok for you if I open a new branch in which I add the possibility to remove the download button (for example adding an optional argument to the embed method)?

Luca

**Comment by modehnal** [comment]
Hi,

we actually added downloads based on Issue #6. Since we have instances where the the embedded text is too long. Having the download for screens and videos was a bonus but the main goal was to download large chunk of text.

I am sure the download button could be disabled via config .ini file, but in our case that would not make much sense.

In your case the download button is somehow in a way or bothering the end user? I am not sure how removing the button would make that much difference.

However that is personal opinion, we plan make the clickable [Download] text a proper button in the future and perhaps even move it to another place, that is still undecided. 

While I am not strictly against having an option for download button, I do not think we should have an option for everything and let the user shoot themselves in the foot.

**Comment by fpokryvk** [comment]
Another possibility is to disable download for small text (e.g. below 20 lines). That is easily doable and probably best solution. We can decide on limit (whether to make it fix or configurable).

**Comment by lu-maca** [comment]
This would not be an option in the config .ini file. My first idea was simply to add an optional argument to the embed function, something like:

```
def embed(self, mime_type, data, caption=None, fail_only=False, is_downloadable=True):
        embed_data = Embed(mime_type, data, caption, fail_only, is_downloadable)
        # Find correct scenario.
        self.current_feature.embed(embed_data)
        return embed_data
```

and in the step implementation:
```
def generate_embed(self, embed_data):
        [...]
        with div(cls="messages"):
            with div(cls="embed-capsule"):

                # Embed Caption.
                with div(cls="embed_button collapse"):
                    with div(cls="link"):
                        # Label to be shown.
                        embed_id = f"embed_{embed_data.uid}"
                        with a(
                            href="#/",
                            onclick=f"collapsible_toggle('{embed_id}',this)",
                        ):
                            span(use_caption)
                        # Download button

                with pre(
                    cls="embed_content",
                    id=f"embed_{embed_data.uid}",
                    style="display: none",
                ):
                    if embed_data.is_downloadable:
                        args = f"'embed_{embed_data.uid}','{use_caption}'"
                        onclick = f"download_embed({args})"
                        a(
                            "[Download]",
                            href="#/",
                            cls="embed_download",
                            onclick=onclick,
                        )

```

In our case, we simply embed in the report all the logs we have, and usually are shorts comments; in the log method we call the `ctx.embed` method with `is_downloadable=False` and the result is something like:

![immagine](https://user-images.githubusercontent.com/65252677/211542107-d0496228-4a0d-4262-ac05-9c2ccfa44330.png)

**Comment by fpokryvk** [comment]
Argument is also fine, I would call it `download_button`, possible values: None, True, False, None meaning default - e.g. we do not want download of links probably (makes no sense) and small messages (below some threshold), True will force the download button even on places where None would hide it, False will disable download button on that embed.

**Comment by modehnal** [comment]
>```
> def embed(self, mime_type, data, caption=None, fail_only=False, is_downloadable=True):
>```
I like this idea.

Along with @fpokryvk idea to make download button with a limit. I have gone over a few of our logs and limit would be very useful as well, there is no reason to have download buttons for one line string.

**Comment by fpokryvk** [comment]
Great! @lu-maca is proposed solution OK? With default None having "mixed" behaviour, but can be forced to True or False, if needed.

**Comment by lu-maca** [comment]
> Great! @lu-maca is proposed solution OK? With default None having "mixed" behaviour, but can be forced to True or False, if needed.

Sure. However I need for some rules about when to disable or not the download button, since I've not so much experience in using the embed method (as said, we use it only for text).

**Comment by modehnal** [comment]
@lu-maca I will take care of the rules. For now create a new branch do your desired changes and I will finish the rest and commit changes to your branch, is that alright?

**Comment by lu-maca** [comment]
[Here](https://github.com/behave-contrib/behave-html-pretty-formatter/tree/fp/disable-embeds-download) the new branch! 

Thank you guys.

**Comment by modehnal** [comment]
I have to finish some stuff but I would say I will be able to get to this tomorrow.

**Comment by modehnal** [comment]
@lu-maca just to let you know, you created branch fp/disable-embeds-download the 'fp' are initials of @fpokryvk. Next branch create something like devel/\<branch\> or lumaca/\<branch\> so we know who created it.

**Comment by lu-maca** [comment]
Oh sorry, I thought that fp was something like "feature p-something"! Next time I will call it with the right name :)

**Comment by modehnal** [comment]
@lu-maca Alright, I have tested it the best I could think of and we are finally happy with the code. Feel free to open Pull Request.

**Comment by modehnal** [comment]
Solved by #23

**Comment by lu-maca** [comment]
@modehnal are you planning to release a new version that includes this change?

**Comment by modehnal** [comment]
@lu-maca We are not currently, this feature in quite small to do a version just for it.

I believe you can still install it by _pip3 install git+repository_. Give it a try and hopefully it will work for you.

Next version was planned after some cleanup and other issues solved so that we are not releasing new versions after every single change. I admit I am quite busy with other issues now that take priority, so I am not sure how soon the new version will be.

**Comment by modehnal** [comment]
Perhaps we could create minor version like 1.4.1 if it was necessary. What do you think @fpokryvk  ?

**Comment by fpokryvk** [comment]
@lu-maca @modehnal Hi, I do not want to promise anything, but I plan to focus on issues next week, hopefully. @modehnal subversioning like that is fine with me.

**Comment by lu-maca** [comment]
Regarding versioning @modehnal, maybe it would be useful to add a versioning tool like [standard-version](https://github.com/conventional-changelog/standard-version) (but is deprecated, don't know why) or the one which is recommended [release-please](https://github.com/googleapis/release-please).

**Comment by modehnal** [comment]
So from the little I have read about this project, I do not really think we should use this.

I suppose the main motivation to use this is to release the new version as soon as pull request is accepted. But we do not want to make multiple releases when we decide we will do each issue in separate pull request and do a single release with more features.

I believe this project is way too small to use tool like this. We are already doing CHANGES when committing changes. So instead of doing CHANGES on our own we would have to carefully craft commit messages. I do not see the upside here.

I would say the delay in releasing this feature is rare, since we have been occupied with other issues that required our attention.

What do you think @fpokryvk. At the end of the day, its not only up to me, if most of you think its a good idea I can be persuaded.

**Comment by modehnal** [comment]
The 1.5 was released and is available to be installed from pip.

**Comment by lu-maca** [comment]
> I believe you can still install it by pip3 install git+repository. Give it a try and hopefully it will work for you.

Sorry for the late answer: yes, until now I was building by myself the app in the right branch.

About versioning, having a versioning automated system is in my opinion much more convenient, since you don't have to update it manually every time. However I agree that the project is small and maybe is not essential to have it.
