### ISSUE TITLE
Add atexit decorator

### ISSUE THREAD

**Issue by lu-maca** [behave-contrib/behave-html-pretty-formatter#34]
Hi,

it's been a while since the last time I opened an issue.

This is a proposal for a new feature. I'm not sure if this is practically possible and don't know what is the real effort required to add it, but I guess it is theoretically feasible. 

We are testing an environment that shall be configured before every scenario starts; thus, we have some configuration background steps (that basically perform the setup and the cleanup of the environment). If something goes wrong in this background step, `sys.exit()` is invoked, because it means that the system itself is not configured in the right way and test procedures cannot be performed (every scenario would fail). In this case, the html report will not be completed, thus it will be impossible to read.

Is there any chance to add an `atexit.register(unexpected_exit)` in the formatter that completes the html report?
What do you think? I guess this is not a so common need, but this is the first time I face this case.

Thanks,
Luca

**Comment by fpokryvk** [comment]
Hi,

we can definitely work on that. We used to have some `sys.exit()` in our tests too, but rather than tweaking the framework (which we also tried), we get rid of `sys.exit()` calls and raised exceptions instead.

The only place where `sys.exit()` remained was in `after_all()` because we need to tweak the exit code for skipped tests. And so we do a little hack in `after_all()` too:
https://gitlab.freedesktop.org/NetworkManager/NetworkManager-ci/-/blob/main/features/environment.py#L376

So, maybe rather than implementing it in formatter directly, maybe try in `before_all()` to register `atexit` that would close the formatters (if not closed already, and I do not know if it is possible to check if it is open, if not, it should not be hard to implement the check for close of the formatter, by setting some attribute if `close()` got called).

Hope this helps.

**Comment by fpokryvk** [comment]
Also keep in mind, if you `sys.exit()` in `before_scenario()` (or sooner), then scenario is not registered in scenario (behave calls formatter after calling the `before_scenario()`. You can tweak this by calling `formatter.scenario()` in `before_scenario()`, but that should be done only if code will not continue and scenario will not be executed, otherwise behave calls `formatter.scenario()` the second time and it is twice in HTML report then.

**Comment by lu-maca** [comment]
> Hi,
> 
> we can definitely work on that. We used to have some `sys.exit()` in our tests too, but rather than tweaking the framework (which we also tried), we get rid of `sys.exit()` calls and raised exceptions instead.
> 

Hi @fpokryvk, hope everything is good :)

When you raise an exception in a step, behave should catch it and make the step fail, but the next scenario should be run anyway, shouldn't it? If the answer is affirmative as I believe, raising an exception would have a different result with respect to call `sys.exit()`: we would like to stop behave, not to skip the scenario (all the others would fail).

> So, maybe rather than implementing it in formatter directly, maybe try in before_all() to register atexit that would close the formatters (if not closed already, and I do not know if it is possible to check if it is open, if not, it should not be hard to implement the check for close of the formatter, by setting some attribute if close() got called).

Maybe a solution would be to wrap the `sys.exit()` with a function that calls the `formatter.close()` method before calling `sys.exit()`?

**Comment by fpokryvk** [comment]
> Maybe a solution would be to wrap the `sys.exit()` with a function that calls the `formatter.close()` method before calling `sys.exit()`?

That would definitely work and is probably the best to start with. Then you will see what report is generated. I guess report will be nearly empty, maybe feature header will be there. But I might be wrong, it really depends how the project code is written.

If you raise exception in `before_scenario` then scenario should not be executed, however `after_scenario` will be, and the same should hold for `feature`, but I have not tested that. The next scenario will call `before_scenario` again, however if you set some private attribute of `context` (private mean starting with `_`, e.g. `context._env_except=True`), then you can raise right away at the beginning of `before_scenario`.

But it is a questionable, if there is still worth in the scenario being in the report, when it was skipped (report would be blue). However, if you embed some data for debug beforehand, then it make sense, otherwise the embeded data would be lost (there is no place where they could be emebeded).

**Comment by modehnal** [comment]
I would like to illustrate how we deal with the environment.py in our projects, in majority of cases we use something similar to what you can see below.

As you can see we also use sys.exit() at some places. For us when code reaches the sys.exit, it means the setup was done wrong, e.g. user error, and it should be looked at. At that moment it has no value for us to generate html report since the very setup of our testing environment was wrong.

But I can see what you are trying to achieve and when I think about it more it would be useful to us too. Even if the setup was wrong, provide html that has the error present so we know where the issue is. We have a way to see what went wrong even without the html report, but that is a part of our testing pipeline which is irrelevant here.

We will try to look into it, so that the traceback from wrong setup can end up in the html - we even have a place for it, before_scenario pseudo_step @fpokryvk :-) we can use that pseudo step as the single entry in the html report and attach the traceback so the problem is clearly visible. 

At least we will try, we might end up clashing with behave since the before_scenario will not be finished, but I have not tested it yet, it also might be much easier than I think.

```python
#!/usr/bin/env python3

"""
This file provides setup for machine environment for our testing pipeline.
"""

import sys
import traceback


def before_all(context) -> None:
    """
    This function will be run once in every 'behave' command called.
    """

    try:
        ###

    except Exception as error:  # pylint: disable=broad-except
        print(f"Environment error: before_all: {error}")
        traceback.print_exc(file=sys.stdout)
        sys.exit(1)


def before_scenario(context, scenario) -> None:
    """
    This function will be run before every scenario in 'behave' command called.
    """

    try:
        ###
    except Exception as error:  # pylint: disable=broad-except
        print(f"Environment error: before_scenario: {error}")
        traceback.print_exc(file=sys.stdout)
        sys.exit(1)


def after_scenario(context, scenario) -> None:
    """
    This function will be run after every scenario in 'behave' command called.
    """

    try:
        ###
    except Exception as error:  # pylint: disable=broad-except
        print(f"Environment error: after_scenario: {error}")
        traceback.print_exc(file=sys.stdout)

```

**Comment by fpokryvk** [comment]
@modehnal sure, we could use the pseudo steps provided that some scenario is registered in in formatter. In Networkmanager, we hack that this way for skipped scenarios, can be done something similar for environment fails:

https://gitlab.freedesktop.org/NetworkManager/NetworkManager-ci/-/blob/main/nmci/embed.py#L124

which is then used in skipped scenarios:

https://gitlab.freedesktop.org/NetworkManager/NetworkManager-ci/-/blob/main/features/environment.py#L53
My point is, it does not seen to be doable in-formatter only, and some additional adjustments of the projects are required. The question is what would be the most optimal (least fragile) solution.

**Comment by modehnal** [comment]
You are right, the sys.exit will just end the run, with nothing more being executed. The project will need some adjustments.

**Comment by lu-maca** [comment]
@modehnal thanks for your comment. 

As @fpokryvk pointed out, if I call `sys.exit()` in a background step, the formatter treats the scenario as if it were skipped.

A more effective solution it is the following:

``` python
class Logger: 
    """
    a logger class that mimics a logger
    """
    def __init__(self, logging_level: str):
        self.__isCritical = False
        self.__loggingLevel = logging_level
    
    def critical(self, message):
        # log the message with a custom format
        ...
        # set isCritical: it should be used in after_scenario()
        self.__isCritical = True
        
    def isCriticalRaised(self):
        return self.__isCritical
```

In the `environment.py` then:
``` python
def after_step(ctx):
    if ctx.logger.isCriticalRaised():
        # set the step status to failed; in this way the scenario will be stopped
        step.status = Status.failed

def after_scenario(ctx):
    # perform some actions...
    ...
    # the custom logger has been previously instantiated in ctx
    if ctx.logger.isCriticalRaised():
        for f in ctx._runner.formatters:
            f.close()
        sys.exit()
```

**Comment by fpokryvk** [comment]
Let me give this a thought until tomorrow, I might have some partial solution that can be done in formatter with minimal impact to the projects. But still need to think about the details...

**Comment by modehnal** [comment]
@lu-maca Your solution might be more complicated than it needs to be.

Your first comment might be the go-to solution, I have tested the behavior of `atexit` with `sys.exit` and it works as expected and we might be able to use that as you described.

But as Filip said it will have to wait until tomorrow when better ideas will come to us :smile: (the ideas are always better after a good night sleep)

**Comment by lu-maca** [comment]
@modehnal that's cool  :)

I will wait for news, for now thank you for your job!

**Comment by fpokryvk** [comment]
So, here are some news, with the following code in `before_scenario()`

```python
def before_scenario(context, scenario):
    # setup formatter to be html-pretty
    formatter.embed("text", "xx", "XXX")
    sys.exit(0)
```

I was able to get prety solid report using `atexit` directly in formatter:

![image](https://user-images.githubusercontent.com/41154041/220835809-54f0d4e4-bdc1-4646-b766-d2e36b29b5fc.png)

Since there is no scenario registered to formatter, dummy scenario is created (Unknown scenario) with error message describing what happened, but most importantly, the embed is not lost.

If there would be no emebed done before `sys.exit()` no dummy scenario is added and only feature panel is present.

The code is surprisingly short, see #35.

**Comment by lu-maca** [comment]
Hey @fpokryvk 

I've just tried your changes, however in our case the `sys.exit()` is not called in `before_scenario`, but in a background steps. I don't know exactly when they (background steps) are executed, I guess after the `before_scenario`. So in our case your change does not solve the problem.

The minimal reproducible example is the following:
``` gherkin
Background: 
    Given something goes wrong

Scenario: first
    When foo
    Then bar

Scenario: second
    When foo
    Then bar

Scenario: third
    When foo
    Then bar
```

``` python
from behave import *
import sys

idx = 0

@given('something goes wrong')
def given_something_wrong(ctx):
    global idx
    idx += 1
    ctx.embed("[INFO] Counter" + str(idx))
    
    # call sys.exit()
    if idx == 2:
        sys.exit()

@when('foo')
def when_foo(ctx):
    pass

@then('bar')
def then_bar(ctx):
    pass
```

Here two pictures that describe the differences between your solution (1) and the one proposed [here](https://github.com/behave-contrib/behave-html-pretty-formatter/issues/34#issuecomment-1440401861) (2) with an example that is similar to the one proposed above:

(1) as you can see, with your solution the scenario is shown as skipped, while the background given step has been executed.
![immagine](https://user-images.githubusercontent.com/65252677/220858598-8bfb5ae4-ad00-405c-bf1e-178af977c48a.png)

(2) with the other solution, the scenario is instead shown failed (as it should be) and in particular the background step is red.
![immagine](https://user-images.githubusercontent.com/65252677/220858659-684d66fd-e79a-4e5b-aaf4-5389ee1e32d7.png)

I'm not sure why is like this, my knowledge about the formatter is not as deep as yours :)

**Comment by fpokryvk** [comment]
Hi @lu-maca,

ok, it is much clearer to me now. The report is "blue" because scenario got registered (default state is skipped = blue), but before first step result it exited prematurely. But I think it is a progress from empty report.

I think, by default, we can make scenario status failed and first step failed - but not sure how would that affect explicitly skipped scenarios.

**Comment by lu-maca** [comment]
> But I think it is a progress from empty report

Sure!

> I think, by default, we can make scenario status failed and first step failed - but not sure how would that affect explicitly skipped scenarios.

This is my main concern and I wouldn't solve it in this way.

If I find some solution I will let you know, for now nothing comes to my mind

**Comment by modehnal** [comment]
@lu-maca So while Filip has better understanding about the formatter and can perhaps provide a viable solution, something occured to me that I need to understand.

Why do you need to use `sys.exit`?  As I have tested few solutions, I am effectively trying to create something that already exists. Which is `assert False, "Any error message"` instead of the `sys.exit`. When I use assert in background step the outcome is exactly as you want it, the test will not continue, and there are no changes required on formatter side and you can add any message you might want to the step.

Using assert also does not run to the problems with after_scenario as even with wrong setup, the `after_scenario` might need to be executed for some teardown.

You might have a valid reason for sure, but as of now it really seems that we are trying to reinvent the wheel. What do you think @fpokryvk ?

**Comment by modehnal** [comment]
As an addition to my previous comment. I think there are two different cases here.

First one is the `sys.exit` in environment.py, there I think it is valid since the environment should always be set correctly - plus the solution from Filip is already working for that case, which I think is useful for us too so those changes should get in.

The second one is once the scenario/steps are starting to be executed. I think if you would do the assert you should get a valid solution.

As per your example I would do something like this - now notice I made it fail on the first test, while trying to run them all:
```python
from behave import *
import sys

idx = 0

@given("something goes wrong")
def given_something_wrong(ctx):
    global idx
    idx += 1

    if idx == 1:
        ctx.failed_setup = True
        assert False, "The setup got krangled!"

@when('foo')
def when_foo(ctx):
    pass

@then('bar')
def then_bar(ctx):
    pass
```
Changes in your `after_scenario` in environment.py would look like this:
```python
import sys

def after_scenario(ctx, scenario) -> None:
    """
    This function will be run after every scenario in 'behave' command called.
    """
    if hasattr(ctx, "failed_setup") and ctx.failed_setup:
        sys.exit(1)

```


Which would produce only a single scenario just like you need and the rest will not be there as the `sys.exit` will make sure nothing else will get started.
![formatter](https://user-images.githubusercontent.com/40463522/220920033-da1d0a24-f60e-4b19-9564-646383d10917.png)

Would this be a valid solution for you?

**Comment by lu-maca** [comment]
What you are doing in your proposal is basically what I've written [here](https://github.com/behave-contrib/behave-html-pretty-formatter/issues/34#issuecomment-1440401861); simply in my case I have to set `ctx.failed_setup = True` in a method of a class that lives outside the step file, isn't it?

> **When I use assert in background step the outcome is exactly as you want it, the test will not continue**, and there are no changes required on formatter side and you can add any message you might want to the step.

The bold is not what I mean. Probably I didn't explain well. I'll try here.
If a background step fails for a scenario, then the next scenario is run, for example:
![immagine](https://user-images.githubusercontent.com/65252677/220967842-632ef7c5-88c3-4e08-acf7-7a91e98946b3.png)

There can be situations, let's call them "critical situations", in which if something goes wrong you cannot continue the test run (not only the current scenario, but all the next scenarios!). For example:
``` gherkin
Background: check the connection
    Given the connection is ok

Scenario: first
    When step that needs the connection
    Then ...

Scenario: second
    When step that needs the connection
    Then ...

... and many other scenarios
```
None of them can be run if the background step fails the first time (and if it fails the first time, it will fail also the second, and the third, and so on...). Since background step "connection is ok" (which actually are more background steps) takes something like 30 seconds to fail, having hundreds of scenarios means that you spend a lot lot of time doing something useless. 

Another example is:
``` gherkin
Background: check the connection
    Given the connection is ok

Scenario: first
    When I reboot my tool
    Then the tool reboots correctly

Scenario: second
    When step that needs the tool is up and running
    Then ...

... and many other scenarios
```
If the tool doesn't reboot correctly and the first scenario's Then step fails, what would you do? Well, the other scenarios cannot be run at all! So why should I try to check the connection hundreds of times when I already know that the connection cannot be established since my tool is not running?

These are the first two cases that come to my mind and I can understand they are pretty corner cases (we are testing embedded flight SW ([this](https://www.dorbit.space/) is what we do)) and probably are not so common. This is the reason I called them "critical situations" and that's why we call a `sys.exit()` only when a `critical` message is logged.

Hope this is clearer now :)
Again, thanks for this enlightening discussion!

**Comment by fpokryvk** [comment]
What @modehnal was proposing did not cause the repetitive execution of scenarios.

Simply before assert, set some context variable - `context._scenario_bg_fail = True` and in `after_scenario` do `sys.exit()` if this attribute is set. `after_scenario` is executed if you assert or raise an exception. Then formatter has enough data to format the output properly, and `sys.exit` is safe there, with the formatter version from #35 (and `sys.exit` prevents execution of next scenarios).

**Comment by modehnal** [comment]
I am not sure if we are on the same page.

I understand you need a way to end all following tests after the background step, you do not need them to run since you know for sure they will fail.
> (not only the current scenario, but all the next scenarios!)

From this I would say you assume the solution would run that background step again and fail many times, which it would not as I described here.

> Which would produce only a single scenario just like you need and the rest will not be there as the `sys.exit` will make sure nothing else will get started.

The following also is not accurate.

> I have to set `ctx.failed_setup = True` in a method of a class that lives outside the step file, isn't it?

Behave will keep anything you set to the `context`, or `ctx` as you shorten it, and keep it across all the files you have.

**Comment by fpokryvk** [comment]
Also note, that behave does some cleanup on context, so it is does refresh for new scenario, however if you make the attribute private - prefixed with `_`, this does not get removed and stays there. So for such reason, I would propose private context attribute.

**Comment by modehnal** [comment]
> Also note, that behave does some cleanup on context, so it is does refresh for new scenario, however if you make the attribute private - prefixed with `_`, this does not get removed and stays there. So for such reason, I would propose private context attribute.

Good point thank you.

To expand on the context, you can read about it more in behave documentation https://behave.readthedocs.io/en/stable/api.html?#behave.runner.Context

```
Hold contextual information during the running of tests.

This object is a place to store information related to the tests you’re running.
You may add arbitrary attributes to it of whatever value you need.
```

**Comment by lu-maca** [comment]
> What @modehnal was proposing did not cause the repetitive execution of scenarios.
> 
> Simply before assert, set some context variable - `context._scenario_bg_fail = True` and in `after_scenario` do `sys.exit()` if this attribute is set. `after_scenario` is executed if you assert or raise an exception. Then formatter has enough data to format the output properly, and `sys.exit` is safe there, with the formatter version from #35 (and `sys.exit` prevents execution of next scenarios).

It's exactly what I wrote [here](https://github.com/behave-contrib/behave-html-pretty-formatter/issues/34#issuecomment-1440401861): 

- in `Logger.critical()` I set a boolean that has the same meaning of your `context._scenario_bg_fail = True`
- in `after_scenario` I check it and I call the `sys.exit()` if it is true

It is exactly the same!

**Comment by lu-maca** [comment]
Ok, I'm not so noob, I know what the context is :D

**Comment by lu-maca** [comment]
> The following also is not accurate.
> 
> > I have to set `ctx.failed_setup = True` in a method of a class that lives outside the step file, isn't it?
> 
> Behave will keep anything you set to the `context`, or `ctx` as you shorten it, and keep it across all the files you have.

I meant that I'm not using the ctx to carry `failed_setup`.

The structure of our company framework cannot be described here, but as said above, your solution and the one I proposed are exactly the same. You are simply setting in `ctx.failed_setup` the information about a "failed step", while I'm setting it in a more structure way as an attribute of a Logger object that is itself an attribute of ctx.

**Comment by modehnal** [comment]
> It's exactly what I wrote [here](https://github.com/behave-contrib/behave-html-pretty-formatter/issues/34#issuecomment-1440401861):
> 
> It is exactly the same!

That is true, it was my mistake that I did not realize you are calling the `sys.exit` in your steps.py file at first. That is why I thought it might be too complicated for usage just in environment.py where Filip's solution works just with the `atexit`.


> Ok, I'm not so noob, I know what the context is :D

I did not mean to offend :-)

> The structure of our company framework cannot be described here, but as said above, your solution and the one I proposed are exactly the same. 

Indeed, in that case your solution might be the best here. Since the changes that would need to be done for the `sys.exit` working in steps.py are not that simple while your solution already does the job better.

**Comment by lu-maca** [comment]
Finally we understand each other :D All's well that ends well. Anyway, I think the pull request makes a lot of sense, since it makes the report readable if a sys.exit() happens somewhere

**Comment by fpokryvk** [comment]
@lu-maca, I managed to make change, that sets last step in last scenario to failed, when `atexit` hook is called. Your use case should work without any changes, `sys.exit` in background step made HTML report with single failed scenario. Can you test the code from pull request?

**Comment by lu-maca** [comment]
@fpokryvk it seems it works!

Thank you very much
