### ISSUE TITLE
How to embed multiple screenshots into Behave html report using behave-html-pretty-formatter

### ISSUE THREAD

**Issue by malindajudo** [behave-contrib/behave-html-pretty-formatter#46]
As per the documentation, I have 

`def before_all(context: Context):
    for formatter in context._runner.formatters:
        if formatter.name == "html-pretty":
           context.embed = formatter.embed`

And 

`def after_scenario(context, scenario):
    image_location = "./pytest_results/"
    context.embed(mime_type="image/png", data=image_location, caption="Screenshot")`
    
 All my screenshots are generated inside folder "./pytest_results".  After running the scenarios the behave.html report is successfully generated, but no screenshots are embedded. If I give path for a one png file then same screenshot has been added to all the scenarios. 
 
 Executed cmd :  _behave -f html-pretty -o behave-report.html .\features\test1.feature_
 
 All the screenshots are generated as `{context.scenario.name}_fail_screenshot.png` 
 
 How I can embed multiple screenshots to behave-report.html ? We have more than 500 scenarios and embedding one by one seems not possible. If there is a better way then can I get an example ?

**Comment by modehnal** [comment]
So what you are trying to do is to embed all images you have in the folder only in one scenario, presumably last one?

Perhaps you have your reasons but I am not sure what is the advantage here. Why not have an Image of failed test attached the the Scenario that generated it? Based on `{context.scenario.name}_fail_screenshot.png` I would assume you are generating the image on fail so you can easily attach the image to the scenario only once.

What we do in this regard is having a folder that will be emptied between every test. So that the image you are attaching is there only if error happened in which case you will get embed. In next scenario there is no image so you cannot get embed in the scenario that passed (unless user wants to).

 Which means we are doing embed to `scenario.name` for `{context.scenario.name}_fail_screenshot.png` and each scenario that failed has an image that will hopefully explain what went wrong or at least hint to it.
 
 If you are trying to do embed only once for all images after all (and again I do not see why you would want to do that). You are still able to. While we do not have that feature to allow you to pass a folder and everything will get attached - which does not seem safe - you can implement this in your environment file.
 
 in your `environment.py` in `after_scenario(context, scenario)` you can do:
```python
# We are usually doing matching by tags if we want to target specific scenario.
if  "<tag_of_your_last_test>" in scenario.effective_tags:
    for _file in _file_folder:
        context.embed(mime_type="image/png", data=_file, caption="Screenshot_{context.scenario.name}_fail_screenshot.png")
 ```

This would generate embeds only in the last scenario and all embeds would be located there while having nothing in the previous ones.

Hopefully this helped you a bit. If there is still a misunderstanding here let me know.

Edit: I changed the if to proper format so it can work. The `scenario.effective_tags` is a list.

**Comment by malindajudo** [comment]
Thanks for the reply @modehnal . All the failed screenshots are for different scenarios but generated inside  the same folder. So need to embed correct failure screenshot to correct scenario. Not only the last one. After scenario, embed the screenshot and then emptying the folder for the next scenario run might be feasible. Let me know if you have a better way to do this.

**Comment by modehnal** [comment]
Right so you want to attach failed image to its corresponding scenario, alright, that makes things easier.

So there are two ways that come to mind considering your use case.

**Option one.**
If you want to keep all the images even after the test suite is run - which I think you do not need since you will have them in the report. You can do the embeds as I described. Name them accordingly and you will never have a situation of embed in the wrong scenario.

You would do it like this:
```python
import os
if os.path.exists(f"{context.scenario.name}_fail_screenshot.png"):
    context.embed(mime_type="image/png", data=<file_location>, caption="Screenshot_{context.scenario.name}_fail_screenshot.png")
```
This will make sure that the embed only happens in the scenario that is running if it generated the failed image. In all other cases the images will be named after different scenarios so the if will fail and embed will not get executed.

**Option two.**
You do not need to keep all the images in the folder after the test suite is run (we are using this option since the machine that executed it will get recycled for next test suite, we only get reports out of it). In this case you simply rewrite the single file over and over again. You might have noticed in the original issue you opened, we had the file location as `/tmp/screenshot.png`. It is up to you how you generate it so you have a lot of options.

The actual code looks like this:
```python
# If the test fails, behave will save to `scenario` a status message.
if scenario.status == "failed":
    # You have many options that should fit your solution, but save it as `/tmp/screenshot.png`
    # This will overwrite any previous image so the latest one should always the current scenario.
    _capture_image()
    # You can safely embed the image since you know a few things.
    # 1) the test failed and you want to embed image.
    # 2) the image is the current scenario since you have captured an image just now.
    context.embed(mime_type="image/png", data="/tmp/screenshot.png", "Screenshot")


```

**Comment by modehnal** [comment]
I believe we can close this issue since users have the possibility to embed multiple images. While not supported directly by formatter to embed entire folders of data, the embedding can be done in any way user desires.

If you still have any issues feel free to reopen this issue or file a new one. Thank you for using our formatter :+1:
